# Generated by Django 3.1.5 on 2021-02-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dungeon_type', models.CharField(max_length=16)),
                ('dungeon_name', models.CharField(max_length=200)),
                ('experience', models.IntegerField(default=0)),
                ('stamina', models.IntegerField(default=0)),
            ],
        ),
    ]
